//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.19 at 01:14:40 AM EET 
//


package com.javaquasar.java.core.chapter_18_XML.practice.task_5_02.group;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the buzov.lecture3_06.practice.task_5_02.group package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: buzov.lecture3_06.practice.task_5_02.group
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GroupData }
     * 
     */
    public GroupData createGroupData() {
        return new GroupData();
    }

    /**
     * Create an instance of {@link GroupData.StudentsData }
     * 
     */
    public GroupData.StudentsData createGroupDataStudentsData() {
        return new GroupData.StudentsData();
    }

    /**
     * Create an instance of {@link GroupData.StudentsData.StudentData }
     * 
     */
    public GroupData.StudentsData.StudentData createGroupDataStudentsDataStudentData() {
        return new GroupData.StudentsData.StudentData();
    }

    /**
     * Create an instance of {@link GroupData.StudentsData.StudentData.RegistrationCityData }
     * 
     */
    public GroupData.StudentsData.StudentData.RegistrationCityData createGroupDataStudentsDataStudentDataRegistrationCityData() {
        return new GroupData.StudentsData.StudentData.RegistrationCityData();
    }

}
